### ISSUE TITLE
Species - show total number of species in the project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1758]
Design https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=8831-63106&mode=design&t=LeyjPI5P2ut6rJBf-4

- [ ] Show total number of species in the project 
- [ ] API - [TBD]

![Image](https://github.com/rfcx/arbimon/assets/87486094/8412e4c2-9bb6-4850-ba2f-73eb2476ee67)

## Expected result
- [ ] User can see total of added species in the project 
- [ ] Number of total species matches with the list

**Comment by RatreeOchn** [comment]
<img width="1345" alt="Screenshot 2567-12-03 at 15 34 53" src="https://github.com/user-attachments/assets/cce5f100-79f9-4beb-a419-f73d1c920217">
