### ISSUE TITLE
Ability to add species from visualizer

### ISSUE THREAD

**Issue by carlybatist** [rfcx/arbimon#1778]
From @carlybatist on Slack - https://rfcx.slack.com/archives/C06Q8RB97A6/p1710868292722079

We want to be able to add a species to the project directly from the Visualizer, so something like when you click on ‘Species Validations’ there would be a new ‘Add Species’ button that would prompt the same pop-up you get when adding a species from the actual Explore>Species page.

Right now, if you are manually annotating spectrograms in the Visualizer and you find a new species you want to add to project, you have to open arbimon in a new tab, go to species page and add that species, then go back to the visualizer tab and refresh so the new species will show up.
Being able to directly add a species from the Visualizer itself would make this process much more streamlined and efficient.

There are 2 places we could include this 'Add Species' option, one in the left-side panel under 'species presence validation' (first screenshot below) and also when someone is drawing a template and choosing a species for it (second screenshot)  

![Image](https://github.com/rfcx/arbimon/assets/46716228/9bed18c7-ecec-426f-a51c-fb2c515858e5)

<img width="433" alt="Screenshot 2024-05-07 at 9 20 01 AM" src="https://github.com/rfcx/arbimon/assets/46716228/c59d7d2c-0398-4645-aa91-3bb54561ba5e">

**Comment by koonchaya** [comment]
Feedback after review call for adding species from visualizer

- Auto-scroll to the selected/added species on the side panel
- Add the message to notify user that species has been added (same as add species from template popup)
- Increase time of the added species message
+ known bugs 
- [Adding new species still show added species with search for species (default) after I selected existing species once before adding new species.](https://rfcx.slack.com/archives/D01L69AJTFC/p1718189611979999?thread_ts=1718182179.759349&cid=D01L69AJTFC)
- [It should show the search input while user selecting the species to add (not the previous selected one)](https://rfcx.slack.com/archives/D01L69AJTFC/p1718189898763709?thread_ts=1718182179.759349&cid=D01L69AJTFC)

We can include this change to the next release

**Comment by rassokhina-e** [comment]
@koonchaya please check the cases above

**Comment by koonchaya** [comment]
@rassokhina-e 
- [ ] After input search species, the pointer changed to zoom in icon when hovering over spectrogram.
- [ ] This case is still happening only during selecting species call [Adding new species still show added species with search for species (default) after I selected existing species once before adding new species.](https://rfcx.slack.com/archives/D01L69AJTFC/p1718189611979999?thread_ts=1718182179.759349&cid=D01L69AJTFC) 

https://github.com/rfcx/arbimon/assets/87486094/3c7c5ee0-86e7-428a-bf5d-5ddef9959a11

**Comment by rassokhina-e** [comment]
@koonchaya I acnnot find this case, please attach the video:
> After input search species, the pointer changed to zoom in icon when hovering over spectrogram.

**Comment by koonchaya** [comment]
additional case to fix https://rfcx.slack.com/archives/D01L69AJTFC/p1718631461835859?thread_ts=1718387670.117279&cid=D01L69AJTFC

**Comment by rassokhina-e** [comment]
can you please check this case @koonchaya on the staging side

**Comment by koonchaya** [comment]
Feedback 
- https://rfcx.slack.com/archives/D01L69AJTFC/p1718806508219809 
- https://rfcx.slack.com/archives/D01L69AJTFC/p1718806712009539

**Comment by rassokhina-e** [comment]
>Deleting species didn't delete search text

it shouldn't be a clear icon for the search text, I removed it



![Image](https://github.com/rfcx/arbimon/assets/31901584/cfb4e1bf-9e1f-4c7b-842c-c0567f9c14a0)



![Image](https://github.com/rfcx/arbimon/assets/31901584/1c8484c0-6aab-4748-b8ed-7a07c7b2c211)

**Comment by rassokhina-e** [comment]
>The overlap text is still there for the case that when I search for a species after added the new species.

>The overlap text is still there for the case that when I search for a species after added the new species and select a species. Species and search text are overlaping

similar cases

I clear the search after adding a new class



![Image](https://github.com/rfcx/arbimon/assets/31901584/1b9e7550-1b70-4ee4-bb46-8ef027d1f201)



![Image](https://github.com/rfcx/arbimon/assets/31901584/5ed6e778-c7bf-42d6-a9fd-8952426d5d4f)



![Image](https://github.com/rfcx/arbimon/assets/31901584/7fbc240c-f8ff-453e-8631-1763bfd02a37)
