### ISSUE TITLE
Ability to upload photos to sites directly in Arbimon

### ISSUE THREAD

**Issue by carlybatist** [rfcx/arbimon#1781]
From @carlybatist on Slack (via Kris' previous request): https://rfcx.slack.com/archives/C06Q8RB97A6/p1710866371094229

Be able to upload site photos to Arbimon directly, without using the companion app. 
Sometimes photos don’t sync when the deployment syncs, and then they never make it into Arbimon. The only way to add anything afterwards is to just re-do the deployment in the app, but that affects other things like the most recent deployment date/time, etc. There should be a way to upload site photos directly to Arbimon, in the 'Sites' page.

**Comment by antonyharfield** [comment]
No longer relevant
