### ISSUE TITLE
CNN Export - export all model detections

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1897]
## Background

Figma: https://www.figma.com/file/FGnP9kAFLDmraAFJf8OBAG/CNN-Roadmap?type=design&node-id=1883-15052&mode=design&t=4CbJ678wpH4hog1A-4

![image](https://github.com/rfcx/arbimon/assets/9149523/3d587605-d6a2-4a88-b0cf-b7bada4dddfa)

MVP version will only allow the user to export "all model detections"

## Expected results
- [x] User sees export button on summary page
- [x] When user clicks on export button on summary page, export results pop up opens
- [x] User can see sample of the export file on the pop up
- [x] User can export file from the pop up
- [x] User gets the export file in the email (like PM)
- [x] When user clicks on cancel button, the pop up will close
- [x] Export file should have the columns follow this example [detections_001.csv](https://github.com/rfcx/arbimon/files/15506069/detections_001.csv)
## Related APIs
- [ ] CNN export - cron-job to call to trigger an export script & send email to the user
- [x] #1895

**Comment by grindarius** [comment]
Released on [v1.4.0](https://github.com/rfcx/arbimon/releases/tag/v1.4.0)
