### ISSUE TITLE
CNN - confirm to cancel popup

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1901]
### Expect results
- [x] when the user click "Cancel" show this popup 
  <img width="391" alt="Screenshot 2024-05-28 at 10 01 26 AM" src="https://github.com/rfcx/arbimon/assets/47339266/984ced25-bc01-4c0e-89bf-1e4f7f77f743">

  [figma
](https://www.figma.com/design/FGnP9kAFLDmraAFJf8OBAG/CNN-Roadmap?node-id=2343-14184&t=qwDm46tvlZdqvJly-1)

- [x] It should be implemented in both CNN list page & summary page (where you can click to cancel the job)

**Comment by grindarius** [comment]
Released on [v1.4.1](https://github.com/rfcx/arbimon/releases/v1.4.1)
