### ISSUE TITLE
Ability to filter project directory by private vs. public projects

### ISSUE THREAD

**Issue by carlybatist** [rfcx/arbimon#1963]
Add a filter in project directory that allows you to search for only published projects

**Comment by koonchaya** [comment]
![Image](https://github.com/user-attachments/assets/ae7144a2-cc34-49ce-8d25-a6a8bf2fe70d)
![Image](https://github.com/user-attachments/assets/07f0e7f4-e882-46cc-bb6c-10ae7e4311d2)

**Comment by koonchaya** [comment]
Updated design

:ballot_box_with_check: Only projects with published insights
