### ISSUE TITLE
Change UI of user roles on member page

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1980]
## Context
The current user roles description is hard to understand exactly the user can do. We want. to improve it to be easier to understand. The current what each roles can do is in the current results sheet in here https://docs.google.com/spreadsheets/d/1-Pw1e43pF9bzHkbEKA0R2nXObo7VTZaebrKZNtup9XQ/edit#gid=631443903

Design 📸 https://www.figma.com/design/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?node-id=10715-2097&t=2qozYTcVp2nQ4OkR-4

<img width="405" alt="Screenshot 2567-05-28 at 10 02 58 AM" src="https://github.com/rfcx/arbimon/assets/87486094/18437403-02d6-49b2-8865-7e84b1e49950">
<img width="961" alt="Screenshot 2567-05-28 at 10 02 43 AM" src="https://github.com/rfcx/arbimon/assets/87486094/80762074-7988-420d-8c0f-a10396c328ed">

## Expected results
- [ ] User can open member page and see the user roles capabilities
- [ ] Default on owner

**Comment by grindarius** [comment]
Released on [v1.4.0](https://github.com/rfcx/arbimon/releases/tag/v1.4.0)
