### ISSUE TITLE
CNN - minimum confidence add/subtract 0.1 when click on up/down button

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2001]
## Context
When user changes the minimum confidence filter by using the up and down button, it comes to 1 or 0 which are the most and least number. It would be better to add or subtract number with 0.1 when user clicks the button at a time. 

![Image](https://github.com/rfcx/arbimon/assets/87486094/ba07f281-51ba-4b35-9828-998b7e0fb1d7)

**Comment by grindarius** [comment]
Released on [v1.4.0](https://github.com/rfcx/arbimon/releases/tag/v1.4.0)
