### ISSUE TITLE
Disable web uploader

### ISSUE THREAD

**Issue by carlybatist** [rfcx/arbimon#2021]
Disable web uploader because it doesn't have full functionality, it differs from the Uploader App, not as reliable/accurate, easier for users to be confused/make mistakes. 

@tiffanylee0125 to create new UI for ‘Import’ page 
- Just have static page directing to download Mac or Windows uploader app and directing to [support page ](https://help.arbimon.org/collection/176-import)
- Remove dropdown - just have 'Import'

![Image](https://github.com/rfcx/arbimon/assets/46716228/2369d0ee-9383-426e-a903-1973807e85de)

- Add a button on Explore Recordings to go to download uploader

**Comment by koonchaya** [comment]
- Open Import>Recordings from side menu will redirect to new page
- Open with the old link https://staging.arbimon.org/project/bci-panama-2018/audiodata/uploads/ redirects to new page

**Comment by RatreeOchn** [comment]
Released on [v1.4.2](https://github.com/rfcx/arbimon/releases/tag/v1.4.2)
