### ISSUE TITLE
CNN Export - add error message

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2025]
> Extra cases 
> - Server error: message "There was a system error. Please try again."
> - The job is already in queue for each user: "Your request is still processing. Please try again later."
> The problem is that the api doesn't support export status, so we cannot identify job status.  

 _Originally posted by @koonchaya in [#1897](https://github.com/rfcx/arbimon/issues/1897#issuecomment-2147229891)_

**Comment by grindarius** [comment]
Released on [v1.4.0](https://github.com/rfcx/arbimon/releases/tag/v1.4.0)
