### ISSUE TITLE
Overview - Add error states on Analyses 

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2026]
> @RatreeOchn Can you continue the cases on legacy side from this [doc ](https://docs.google.com/spreadsheets/d/1KS7eopeRPnrVNRrcXsaBBfX2mQWXNTsMPEVvrYMn7Wo/edit?usp=sharing)? Please do the ones that is not highlighted. 

 _Originally posted by @koonchaya in [#1745](https://github.com/rfcx/arbimon/issues/1745#issuecomment-2149222077)_

**Comment by grindarius** [comment]
Released on [v1.4.0](https://github.com/rfcx/arbimon/releases/tag/v1.4.0)
