### ISSUE TITLE
Add and change species in the database

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2034]
Original request: https://rfcx.slack.com/archives/C03FD1WD02J/p1718058512008439

A user requested species adds and I've cross-referenced with existing species in the DB (and with GBIF and IUCN) such that the following changes should be made:

- [x] Change: Amazilia saucerottei --> Saucerottia saucerottei
https://www.iucnredlist.org/species/22687590/167101232
https://www.gbif.org/species/10755999
- [x] Change: Hylopezus dives --> Myrmothera dives
https://www.iucnredlist.org/species/22729072/140516951
- [x]  Change: Chlorothraupis carmioli --> Habia carmioli
https://www.iucnredlist.org/species/103811314/119464504
- [ ] Add: Leuconotopicus fumigatus
https://www.iucnredlist.org/species/22681193/141047835
https://www.gbif.org/species/9000455
- [ ] Add: Xenops rutilus
https://www.iucnredlist.org/species/22702998/168545979
https://www.gbif.org/species/10742392

**Comment by carlybatist** [comment]
One more (again...lol)

Change: Automolus ochrolaemus cervinigularis --> Automolus cervinigularis
(subspecies elevated to species level)
https://www.iucnredlist.org/species/244681681/233324704

**Comment by rassokhina-e** [comment]
@carlybatist is `Picoides fumigatus` synonums the of `Leuconotopicus fumigatus` ?

>Add: Leuconotopicus fumigatus
https://www.iucnredlist.org/species/22681193/141047835
https://www.gbif.org/species/9000455

**Comment by rassokhina-e** [comment]
@carlybatist I also found `Xenops rutilans` in the db, if I put this species to the google it highlight the same species photo. Can you please recheck it?



>Add: Xenops rutilus
https://www.iucnredlist.org/species/22702998/168545979
https://www.gbif.org/species/10742392

**Comment by koonchaya** [comment]
>Amazilia saucerottei --> Saucerottia saucerottei
There are more species using this species name but might be different than the one that Carly requested. Not sure if we want to change them too or not. @carlybatist 

![Image](https://github.com/rfcx/arbimon/assets/87486094/f40dc0e7-839c-4454-b0a7-4bd30562b5de)


![Image](https://github.com/rfcx/arbimon/assets/87486094/fd6e7d44-aa48-49c0-a0a0-047019165362)
![Image](https://github.com/rfcx/arbimon/assets/87486094/a55e85ea-f94a-4ff6-b471-fe70c9dd2783)

**Comment by carlybatist** [comment]
> @carlybatist is `Picoides fumigatus` (this species in the db) synonym of the `Leuconotopicus fumigatus` ? If yes, I can change the name, not add a duplicate
> 
> > Add: Leuconotopicus fumigatus
> > https://www.iucnredlist.org/species/22681193/141047835
> > https://www.gbif.org/species/9000455
> 
> The smoky-brown woodpecker (Leuconotopicus fumigatus)
> 
> ## Synonyms
> Veniliornis fumigatusPicoides fumigatusDryobates fumigatus
> 
> [Synonyms](https://en.wikipedia.org/wiki/Synonym_(taxonomy)) Veniliornis fumigatus Picoides fumigatus Dryobates fumigatus

Yes you can change Picoides fumigatus to Leuconotopicus fumigatus

**Comment by carlybatist** [comment]
> > Amazilia saucerottei --> Saucerottia saucerottei
> > There are more species using this species name but might be different than the one that Carly requested. Not sure if we want to change them too or not. @carlybatist
> 
> ![Image](https://private-user-images.githubusercontent.com/87486094/339663863-f40dc0e7-839c-4454-b0a7-4bd30562b5de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODgzNTYsIm5iZiI6MTcxODM4ODA1NiwicGF0aCI6Ii84NzQ4NjA5NC8zMzk2NjM4NjMtZjQwZGMwZTctODM5Yy00NDU0LWIwYTctNGJkMzA1NjJiNWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE4MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDZmNmMyY2VkMTIzZWZkNTQwZDFmNjM5YzZhMmM3ZGFhZmI5ODU0ZjI0NTI3ZGJiNzljMzMzODZmZWQxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tV68nMbFi-tj6fvBsl4ehlA-Zh67E0t_yqJ2m9u9nFM)
> 
> ![Image](https://private-user-images.githubusercontent.com/87486094/339664685-fd6e7d44-aa48-49c0-a0a0-047019165362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODgzNTYsIm5iZiI6MTcxODM4ODA1NiwicGF0aCI6Ii84NzQ4NjA5NC8zMzk2NjQ2ODUtZmQ2ZTdkNDQtYWE0OC00OWMwLWEwYTAtMDQ3MDE5MTY1MzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE4MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllN2QxZWYyMWExNzRhNWY3OGExMTI0Y2ExNThhOTFjMWVjZDM2NDA4YjMzOTdmZjZmOTAzYmRjYmY5NmY0YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulKajDCgVAw9CEnsxJFv5c03MX15inBbcVV_rrsWIxM) ![Image](https://private-user-images.githubusercontent.com/87486094/339664684-a55e85ea-f94a-4ff6-b471-fe70c9dd2783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODgzNTYsIm5iZiI6MTcxODM4ODA1NiwicGF0aCI6Ii84NzQ4NjA5NC8zMzk2NjQ2ODQtYTU1ZTg1ZWEtZjk0YS00ZmY2LWI0NzEtZmU3MGM5ZGQyNzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE4MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlODc4YzBjNGViYTIxMTJhZDM3ZjhiNjU0ODQ5OGQyNWY2NjhkNTVkMjU3NDU0MWYzOWRhNzBmNTBkYjNlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ngmQQwBrrSHHKTGcGCs85JAc9Nw3T3Y18CA6CQu_1M)

@koonchaya no those are subspecies, leave as is

**Comment by carlybatist** [comment]
> @carlybatist I also found `Xenops rutilans` in the db, if I put this species to the google it highlight the same species photo. Can you please recheck it?
> 
> > Add: Xenops rutilus
> > https://www.iucnredlist.org/species/22702998/168545979
> > https://www.gbif.org/species/10742392

Yes, change Xenops rutilans to Xenops rutilus @rassokhina-e

**Comment by rassokhina-e** [comment]
@carlybatist done!
