### ISSUE TITLE
Create alert when RFM and soundscape jobs are stuck after 6 hours

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2038]
When user created jobs (soundscapes or RFM) and jobs stop running or not started for 6 hours, we should have alert (grafana logs) to show up in arbimon-dev channel. So we know that we have jobs stuck in queue.

**Comment by koonchaya** [comment]
Where do we see this alert? Will we get notification somewhere?

**Comment by rassokhina-e** [comment]
yes, we got test alert in the slack channel

![Image](https://github.com/rfcx/arbimon/assets/31901584/9effd874-9335-4617-8ab9-4c6c89b4aaad)
