### ISSUE TITLE
Add ability for other team members to restart the server when job stuck in queue

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2039]
We should implement the way to allow arbimon team to be able to restart the server so that the jobs can be restarted and run. Right now only @antonyharfield can do it. It should be easier for other team members to do it.

**Comment by antonyharfield** [comment]
Posted to eng team Slack https://rfcx.slack.com/archives/G018NMPCBHS/p1718616171425519 - to be tested by @rassokhina-e and @RatreeOchn

**Comment by koonchaya** [comment]
@RatreeOchn Please close this ticket after you get through this process.

**Comment by grindarius** [comment]
Released on [v1.4.1](https://github.com/rfcx/arbimon/releases/v1.4.1)
