### ISSUE TITLE
Setup for working with Uploader

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2046]
@RatreeOchn needs to setup to prepare to work with Uploader before Zhenya leaves. It would be good to ask Zhenya to share the knowledge about Uploader and Legacy (eg. manually export data, add species, etc).

**Comment by rassokhina-e** [comment]
@RatreeOchn do you have an access to this repo : https://github.com/rfcx/arbimon-uploader?

**Comment by rassokhina-e** [comment]
please follow these steps:
1. clone the repo to your PC 
2. `nvm use` to switch to the node requested
3. `npm install`
4. run the app `npm run dev`

you should see 1 app window + 3 consoles 

@RatreeOchn

**Comment by RatreeOchn** [comment]
I have done to set up the Uploader on my local.

![Image](https://github.com/rfcx/arbimon/assets/51106210/cdfff920-b3a0-4874-ba8a-b33cbd9883cf)

**Comment by koonchaya** [comment]
@RatreeOchn If your setup works now, you can close this ticket.
