### ISSUE TITLE
Project images on project directory aren't showing in square

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2049]
Original post: https://rfcx.slack.com/archives/C02G4AR2GEL/p1718616808831249

Project directory on Chrome has wrong shape project thumbnails on the left (only chrome)

![Image](https://github.com/rfcx/arbimon/assets/87486094/d9446dda-b28b-459a-a105-4dde74a80f7c)

**Comment by RatreeOchn** [comment]
![Image](https://github.com/rfcx/arbimon/assets/51106210/63b745b1-01f1-48fb-ab8b-af59dbf50679)

**Comment by koonchaya** [comment]
I don't see any project images different sizes on staging.

**Comment by grindarius** [comment]
Released on [v1.4.1](https://github.com/rfcx/arbimon/releases/v1.4.1)
