### ISSUE TITLE
Map isn't showing up on Richness, Activity and Spotlight

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2050]
Original post: https://rfcx.slack.com/archives/C02G4AR2GEL/p1718616808831249

The map is not showing on the activity page of the insights (all browsers - tested on safari + chrome)
Including Richness and Spotlight pages

![Image](https://github.com/rfcx/arbimon/assets/87486094/c0b6fb24-8754-46bf-a4b8-4c15340c7da1)

![Image](https://github.com/rfcx/arbimon/assets/87486094/1a7fa138-2570-43ad-aacc-9f2763971c55)

![Image](https://github.com/rfcx/arbimon/assets/87486094/83e47070-e387-4246-a84d-c7433cd2643a)

**Comment by grindarius** [comment]
Released on [v1.4.1](https://github.com/rfcx/arbimon/releases/v1.4.1)
