### ISSUE TITLE
About section on Insight>highlight isn't showing

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2051]
Original post: https://rfcx.slack.com/archives/C02G4AR2GEL/p1718616808831249

The about section of the highlights is not showing (all browsers - tested on safari + chrome)

![Image](https://github.com/rfcx/arbimon/assets/87486094/16eca593-597b-4896-9580-7820ff843e70)

This issue also affects the project information on project directory 

![Image](https://github.com/rfcx/arbimon/assets/87486094/5179466c-73b3-4c58-855a-b5a0a22fad71)

**Comment by koonchaya** [comment]
First time edit any of the summary section will not show up after save. I have to refresh page.

**Comment by grindarius** [comment]
Released on [v1.4.1](https://github.com/rfcx/arbimon/releases/v1.4.0)
