### ISSUE TITLE
Check error status of model training

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2063]
Original report: https://rfcx.slack.com/archives/C03FD1WD02J/p1719579470914459

A user has reported getting errors on an RFM model training job in this project

https://arbimon.org/project/land-birds-in-french-polynesia/jobs

They have tried running the job with different ROIs but it gives an error every time.
Can you please look into what is causing the error message?

![Image](https://github.com/rfcx/arbimon/assets/87486094/0446b723-cba8-404d-8901-e716cda19cd2)

Updated error and stalled jobs

![Image](https://github.com/rfcx/arbimon/assets/87486094/1a5579ae-88d3-442c-9802-98dc6dd1de3e)

**Comment by koonchaya** [comment]
`Error: cannot analize recordings in parallel Traceback (most recent call last):
  File "/var/lib/arbimon2/jobs/scripts/PatternMatching/train.py", line 382, in <module>
    results = Parallel(n_jobs=num_cores)(delayed(recnilize)(line,workingFolder,currDir,jobId,(patternSurfaces[line[4]]),log,ssim,searchMatch) for line in validationData)
  File "/var/lib/arbimon2/jobs/.env/local/lib/python2.7/site-packages/joblib/parallel.py", line 768, in __call__
    self.retrieve()
  File "/var/lib/arbimon2/jobs/.env/local/lib/python2.7/site-packages/joblib/parallel.py", line 719, in retrieve
    raise exception
JoblibMemoryError: JoblibMemoryError`

Looks like memory issue.

**Comment by RatreeOchn** [comment]
For AT Cri d'alarme Test 1, AT Cri d'alarme Test 2, AT Cri d'alarme Test 3 and AT Cri d'alarme Test 4 the `trained_model_id` is NULL

![Image](https://github.com/rfcx/arbimon/assets/51106210/adf9ca96-358d-43b0-9b8f-ec75e6141fc0)


Can not find any model from `training_set_id = '5752'`

![Image](https://github.com/rfcx/arbimon/assets/51106210/8f5dcdeb-f5b9-47c0-b5d4-a377c7c29499)

**Comment by RatreeOchn** [comment]
```
Error: error saving model into database. Traceback (most recent call last):
  File "/var/lib/arbimon2/jobs/scripts/PatternMatching/train.py", line 592, in <module>
    str(user_id)+" ,"+str(training_set_id)+", "+str(valiId)+" )")
  File "/var/lib/arbimon2/jobs/.env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/lib/arbimon2/jobs/.env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'alarme Test 1', 4 , 'project_6157/models/job_94415_8325_8.mod' , now() , 6157,76' at line 1")
``` 
@koonchaya Can you try to create training set without `'`?

**Comment by rassokhina-e** [comment]
the trained_model_id has null value, because the RFM job was with the issue, this is the user popup to create the job, the job will create with null model and then after the completed state the job service should update the model id

@koonchaya 



![Image](https://github.com/rfcx/arbimon/assets/31901584/3212c5ee-7908-4d0c-8fc9-59d4797b3b90)

**Comment by koonchaya** [comment]
User created a new training model without `'`. 

![Image](https://github.com/rfcx/arbimon/assets/87486094/708315cf-dd64-4a5f-a845-e9102384bb62)
