### ISSUE TITLE
Missing recordings in some sites of the project Threatened birds of the Serra da Prata, Pernambuco, Brazil

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2065]
Original report: https://rfcx.slack.com/archives/C03FD1WD02J/p1719874333950509

Project: https://arbimon.org/p/threatened-birds-of-the-serra-da-prata/overview

I am writing to report some issues with the Arbimon project entitled "Threatened birds of the Serra da Prata, Pernambuco, Brazil" (https://arbimon.org/p/threatened-birds-of-the-serra-da-prata).
Since the new platform layout was released, I have noticed that several recordings are missing - at least 800 for each of the following sites:
- [x]  09
- [x]  11
- [x]  14
- [x]  16
- [x]  18
- [x]  20
- [x]  21

I attempted to re-upload these recordings a few days ago, but they are still unavailable for visualization on the platform. Could you please assist me in fixing this issue?

## Additional details
The sites from above have 800 recordings each in the project 

![Image](https://github.com/rfcx/arbimon/assets/87486094/e1de7b54-3107-464e-840f-cb851709ff9b)

**Comment by rassokhina-e** [comment]
1. we have to check the logs in grafana to understand an original problem. By this query we can see the total count of segments to related stream + last uploaded/updated time.
```
SELECT id, start, "end", sample_count, stream_id, stream_source_file_id, file_extension_id, created_at, updated_at, availability, path
	FROM public.stream_segments where stream_id='k8vuy052kcwz' order by updated_at desc;
```
<img width="1000" alt="Untitled 4" src="https://github.com/rfcx/arbimon/assets/31901584/3acaea1e-de34-45da-978b-5fafb6bec858">

**Comment by rassokhina-e** [comment]
2. the user uploaded recordings more then 7 days ago,so we cannot gett the Grafana logs to check the problem, but we can recover missed recordings  using the script https://github.com/rfcx/core-arbimon-jobs/blob/master/jobs/arbimon/restore-recordings/index.js

**Comment by koonchaya** [comment]
@rassokhina-e Can you use the script to recover the missing recordings for those sites?

**Comment by rassokhina-e** [comment]
yes, I can after fixing the PR project, because I'm using the same repo

**Comment by koonchaya** [comment]
Current recordings

![Image](https://github.com/rfcx/arbimon/assets/87486094/56e63fd2-e0e4-4611-b963-f32e2a09afaf)
