### ISSUE TITLE
Soundscape jobs error/not done

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2069]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1719930273836029

I need to send soundscapes for this project:
https://arbimon.org/project/tnc-rfcx-biodiversity-in-parque-nacional-braulio-carrillo-and-la-selva-oet/jobs

But it seems that some jobs are stuck without any progress (jobs BC48_all_2024, BC53_all_2024 and LS02_all_2024). Also, I’m noticing that it’s taking much longer than normal for the soundscape jobs to complete. Is it possible to check this?

![Image](https://github.com/rfcx/arbimon/assets/87486094/241ccb25-b6e9-4f93-af24-862505c7dacb)

**Comment by koonchaya** [comment]
Current status after restart the job queue. 

![Image](https://github.com/rfcx/arbimon/assets/87486094/73a500e6-ad1f-4610-8114-aa1d1f8f575a)


I think user should create the error/stalled jobs again.

**Comment by carlybatist** [comment]
@koonchaya @rassokhina-e can you please look into why the jobs are giving an error in the first place too though? We should understand why this is happening in the first place
