### ISSUE TITLE
User didn't get the export links

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2079]
User sent species export requests but never get the link

![Image](https://github.com/user-attachments/assets/2f92f4c1-dcf1-4439-bc4f-27aa69227a02)

Project: [Cameroon](https://arbimon.org/p/cameroon-ashej-songmeter-micro/overview) and Puerto Rico

**Comment by koonchaya** [comment]
I tested export (Species detection matrix) from https://arbimon.org/project/cameroon-ashej-songmeter-micro/audiodata/recordings and didn't get any export. 

![Image](https://github.com/user-attachments/assets/96e6d64e-852a-47f5-9970-c7635ff6ebd0)

**Comment by RatreeOchn** [comment]
I found the Export parameters on [Cameroon](https://arbimon.org/p/cameroon-ashej-songmeter-micro/overview) project:
```
user email: guilhermemelo.biologia@gmail.com
user id: 5991
project id: 5304
projection_parameters: {"pm":"all","projectUrl":"cameroon-ashej-songmeter-micro"}
filters: {"project_id":5304}
created_at: 2024-07-16 11:35:05
```

**Comment by RatreeOchn** [comment]
Export parameters on Puerto Rico project:
```
url: puerto-rico-island-wide
user email: jwribeirojunior@gmail.com
user id: 111
project id: 1989
projection_parameters: {"recording":["filename","site","day"],"species":[40135,28358]}
filters: {"project_id":1989,"species_name":["Icterus_portoricensis","Contopus_latirostris_blancoi"]}
created_at: 2024-07-16 18:31:02
```
I'm not found any requests from this project on this table.

**Comment by koonchaya** [comment]
Manually export for PR project

[pattern-matching-export.zip](https://github.com/user-attachments/files/16421953/pattern-matching-export.zip)
