### ISSUE TITLE
Missing species Caprimulgus poliocephalus on legacy pages

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2082]
From bWallauer@janegoodall.org

1. User can find `Caprimulgus poliocephalus` on Spotlight and it says found in 233 recordings 

![Image](https://github.com/user-attachments/assets/43929b75-0c54-44c0-ac75-b95c28c3cb9f)

2. Go to Recordings page => cannot find this species (search in validations) 

![Image](https://github.com/user-attachments/assets/aa0107f4-dbbc-4a55-8465-05cb07f0f7af)

3. Go to Templates page => cannot find templates from this species 

![Image](https://github.com/user-attachments/assets/c68cd0a9-8ca4-424c-af95-c6a680810ea7)

>I am wondering if your tech team was able to work out why I can't open my links to my downloaded data from Arbimon.  Did 

> they make any progress?
> I haven't tried again but I will if you think the function is working now.
> 
> Also, a very strange anomaly has come up with a species (Montane Nightjar Caprimulgus poliocephalus) on our project.  In Overview and Spotlight data of this species, the data result output indicates there are 233 verified records (https://arbimon.org/p/jgi-rfcx-gombe-tz/insights/spotlight/caprimulgus-poliocephalus), yet, when you search for Caprimulgus poliocephalus under RECORDINGS or SPECIES, absolutely nothing shows up.  There is not even a template of this species.
> 
> Even when you open the sample recordings from the link above, the link takes you to a verified recording of Caprimulgus pectoralis - Common Song.
> I have no idea why this is happening, but it is very strange.

**Comment by Tooseriuz** [comment]
the number `233` is correct. this number is from `insight` db which there are 233 rows on `Caprimulgus poliocephalus`. But the issue is when you want to check this in `recording_validations`, there is only 1 ROW in `legacy arbimon` which seem like the data are mismatch.

Also the template name in this project, there is only one that is `Caprimulgus poliocephalus Common Song`

**Comment by koonchaya** [comment]
This is related to https://rfcx.slack.com/archives/C02UYCVRXSP/p1701958253329669
