### ISSUE TITLE
Unable to download PM results from PR project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2084]
User cannot download the result from PM job https://arbimon.org/project/puerto-rico-island-wide/analysis/patternmatching/68641. 

>we need to check  is why we are not able to download the data from the PR jobs that we have already validated. But several 
> jobs in this project give an error when we try to download the result (e.g., https://arbimon.org/project/puerto-rico-island-wide/analysis/patternmatching/68641).

![Image](https://github.com/user-attachments/assets/d5835882-77c2-4fbb-a668-33e6148a7017)

**Comment by RatreeOchn** [comment]
![Image](https://github.com/user-attachments/assets/6016afca-24a8-452c-ae63-8a9674d49780)

**Comment by antonyharfield** [comment]
The error is "maximum execution time exceeded", means that the query took more than 90 seconds.

**Comment by koonchaya** [comment]
[pattern-matching-export.zip](https://github.com/user-attachments/files/16423398/pattern-matching-export.zip)
