### ISSUE TITLE
Check the data in the soundscape export

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2087]
This is the comment for the export - the soundscape output should have decimal numbers between 0 and 1. 
The number are all integer.

Project https://arbimon.org/p/tnc-rfcx-biodiversity-in-parque-nacional-braulio-carrillo-and-la-selva-oet/overview

Export file
https://drive.google.com/file/d/1dQYHnaHqwXAJ-ESMJG-UWl7lCcX2wAxe/view?usp=sharing

**Comment by rassokhina-e** [comment]
The problem with matrix data, I'm checking the calculation now
<img width="1512" alt="Screenshot 2024-08-05 at 12 29 12" src="https://github.com/user-attachments/assets/8c238700-b154-4c43-a186-637143dbd766">

**Comment by rassokhina-e** [comment]
we run the test cases to attach more details about the original reason of integer values. During checking the code, I found this is related to the `normalized` checkbox. The job `BC48_all_2024` hasn't this setting, that is why the result are integer values. If the user select `normalized` checkbox we additionally fetching the soundscape's normalization vector and calculating the result by formula:
```
matrix[y][x] = matrix[y][x] * 1.0 / val
```
`val` is the vector for the specific job, example 900


@koonchaya FYI

**Comment by koonchaya** [comment]
can we rerun the jobs with normalize data? or which value is correct?

**Comment by rassokhina-e** [comment]
yes, also we have to know the threshold value, do they want to keep `0` value on increase it to 0.03?

**Comment by koonchaya** [comment]
I don't quite understand what that value is for and should user always check normalize data for the correct value?

**Comment by rassokhina-e** [comment]
`threshold` is amplitude

Minimum amplitude of detected events (number of standard deviations from the mean of the filter spectrogram)
