### ISSUE TITLE
Check PM jobs progress

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2088]
Check the PM jobs progress from this project https://arbimon.org/project/costa-rica-abc-birdsplus-index/jobs
It looks like the jobs are running very slowly or already stuck.

![Image](https://github.com/user-attachments/assets/e2a56415-f350-4631-bfcd-9b94db7c259b)

**Comment by RatreeOchn** [comment]
Hi @rassokhina-e , I checked, it seems that the PM job is stuck. Can PM jobs be rerun? I mean set state to `waiting` or restart all jobs again. Or should we cancel the job and create a new one?

<img width="981" alt="at 10 38 45" src="https://github.com/user-attachments/assets/5abe81a4-58a4-46fb-8023-db23c6ebce73">

<img width="961" alt="at 10 56 04" src="https://github.com/user-attachments/assets/392899a1-1d28-41c9-8902-74fd56392ce4">

**Comment by rassokhina-e** [comment]
the PM job we process with lambda, we have to rerun the job, but first of all we can check the logs related to this job on the lambda logs

**Comment by rassokhina-e** [comment]
the issue I fund in logs 
```
(mysql.connector.errors.DatabaseError) 1205 (HY000): Lock wait timeout exceeded; try restarting transaction 
```

the user can resta
<img width="1331" alt="Screenshot 2024-08-07 at 12 32 06" src="https://github.com/user-attachments/assets/5f4affff-43f8-44c7-995e-b6d0017cf0ec">
rt these 3 jobs

**Comment by koonchaya** [comment]
@rassokhina-e Do we need to tell user to create those jobs again?

**Comment by rassokhina-e** [comment]
`Dendrocolaptes_sanctithomae_common song_WildMon Pattern MatchingAug 7, 2024 12:48 PM99.1%`
this job was updated, I guess only 2 they need to restart

Crotophaga_sulcirostris_simple call_WildMon
Xiphorhynchus_sussurans_common song_WildMon

**Comment by rassokhina-e** [comment]
`Melanerpes_pucherani_common song_WildMon` last update from Aug 7, 2024 12:29 PM (UTC), its processing slowly

**Comment by koonchaya** [comment]
@rassokhina-e I will let them know to create those 2 jobs. By the way, do you know why the jobs are running really slow?

**Comment by koonchaya** [comment]
Aug 7 - at 8:21 PM status

![Image](https://github.com/user-attachments/assets/fa84690d-b5ea-4a0a-89c9-f52e19e92d5e)

**Comment by rassokhina-e** [comment]
221 PM jobs in a progress now, also they uses a huge playlists

**Comment by rassokhina-e** [comment]
Crypturellus_soui_Common song_WildMon the playlist for this job has 1,395,700 recordings

**Comment by koonchaya** [comment]
@rassokhina-e Can you check if these jobs are still running? 
- Dendrocolaptes_sanctithomae_common song_WildMon
- Melanerpes_pucherani_common song_WildMon

**Comment by rassokhina-e** [comment]
yes, they are in a progress

**Comment by koonchaya** [comment]
9 Aug 2024 9:45AM

![Image](https://github.com/user-attachments/assets/d2539d41-cf6f-4407-a7bb-f42d17e70e4c)

**Comment by rassokhina-e** [comment]
costa-rica-abc-birdsplus-index 2 PM in a progress, the user recreated these 2 jobs, actually, the user cancelled the previous ones, but we just hide these jobs, if they will be done I will unhide them

**Comment by rassokhina-e** [comment]
Crypturellus_soui_common song_WildMon is completed

**Comment by rassokhina-e** [comment]
this job - Dencrocolaptes_sanctithomae_common song_WildMon user is hide, I can Unhide it @koonchaya

**Comment by koonchaya** [comment]
@rassokhina-e @RatreeOchn This job `RU_0012 (52481) 2024` is at 100% for a while. Can you check why it is not completed yet?


![Image](https://github.com/user-attachments/assets/75c94d5b-c358-4501-95ac-b42c7afd0353)

**Comment by RatreeOchn** [comment]
Hi @koonchaya 
```
RU_0012 (52481) 2024
IPE30 (23541) 2023
IPE35 (23495) 2023
```
The 3 jobs above are stuck. I have reset the status to `waiting`.
