### ISSUE TITLE
Check job in Bacalar project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2089]
Project https://arbimon.org/project/bacalar/jobs

Seems like 1 job is stuck at 10%

![Image](https://github.com/user-attachments/assets/93d62009-f173-4653-825e-8b6be27cc745)

**Comment by rassokhina-e** [comment]
52 PM jobs in a waiting status
154 PM jobs in a processing status

with date_created >= '2024-08-07 00:00:00';

I guess the big pressure now to lambdas

> If it is stuck, should user creates it again?
lets wait during this day, a lot of jobs in a progress now, we can check tomorrow

**Comment by koonchaya** [comment]
Looks like user cancel the job already

![Image](https://github.com/user-attachments/assets/b7bdc101-11b7-44d7-8830-307d0df28ea6)

**Comment by rassokhina-e** [comment]
completed jobs

![Image](https://github.com/user-attachments/assets/d8a89356-90de-4a46-82ec-ed66c742d035)
