### ISSUE TITLE
Check species detection matrix for cameroon project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2090]
User said that they haven't received the species detection matrix export yet. Requested from project: https://arbimon.org/p/cameroon-ashej-songmeter-micro/overview

Ref. where to export this request 

![Image](https://github.com/user-attachments/assets/11a3e6e8-9068-4241-b37e-0f840872abb1)

**Comment by rassokhina-e** [comment]
the report sent today
