### ISSUE TITLE
Fix timestamps of Biosoundscape project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2091]
Fix timestamps from UTC to local time
Project https://arbimon.org/p/biosoundscape/overview
Fix the sites listed in this sheet https://drive.google.com/file/d/1vLke6YwRsOWTpkX2u8GdhhRkuvHjUPRm/view?usp=sharing

**Comment by rassokhina-e** [comment]
@koonchaya is it a partner project?

**Comment by koonchaya** [comment]
@rassokhina-e I added the sheet for tracking here https://docs.google.com/spreadsheets/d/1O5IN_B9nlwJulCy4hoU1271q8BK9svyCqA8m3rYBP2k/edit?usp=sharing.
