### ISSUE TITLE
Update the address and phone number on Arbimon

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2099]
Update the address on [Arbimon](https://arbimon.org/contact) and rfcx.org footer

1. Address changes to 

77 Van Ness Avenue
Suite 101-1717
San Francisco CA, 94102

2. Phone number changes to +1 (325) 666-3050

**Comment by RatreeOchn** [comment]
Done for updating the address and phone number on rfcx.org

<img width="1352" alt="Screenshot 2567-08-28 at 13 30 37" src="https://github.com/user-attachments/assets/d1c431b8-565b-42c3-8aea-c471f9cace27">

**Comment by RatreeOchn** [comment]
Done on https://arbimon.org/contact

<img width="1352" alt="Screenshot 2567-08-28 at 13 47 51" src="https://github.com/user-attachments/assets/2cafaebc-c5d4-4930-9fd4-6a099c241db9">

**Comment by koonchaya** [comment]
![Image](https://github.com/user-attachments/assets/1719ff87-caeb-4629-a92c-3cc5e9254a09)
![Image](https://github.com/user-attachments/assets/81ae2186-1f43-4db5-9cc4-88019b1d45d6)
