### ISSUE TITLE
Model training job error

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2103]
From [amandine.delbeauve@gmail.com](mailto:amandine.delbeauve@gmail.com)

Project https://arbimon.org/p/brame-du-cerf

>I uploaded 100 recordings and treated them via the visualizer.
50 of them with the setting "absent" and the other ones with the setting "present".
Then, I tried to create a RFM, with 40 recordings for the fitting and 10 for the validation (for each setting). However, I look at "active jobs", there is an error message "Error communicating with server". Can you tell the signification of this error ? Can you help me ?

![Image](https://github.com/user-attachments/assets/c0284066-79df-4759-a335-45de423d2c74)

**Comment by RatreeOchn** [comment]
I found an error `Error: cannot create validation csvs files or access validation data from db. (no error)` I have checked with the old jobs that also give this error message, and jobs in this project have a tranined_model_id value of null (I tried comparing to completed jobs where their tranined_model_id value was not null)

<img width="1119" alt="Screenshot 2567-09-30 at 11 27 21" src="https://github.com/user-attachments/assets/53c3a533-ada9-4b1d-8785-b495b411d098">

<img width="1154" alt="Screenshot 2567-09-30 at 11 38 45" src="https://github.com/user-attachments/assets/9ae9e883-63f1-4c5e-948b-96063765b255">

[jobs_202409301123.csv](https://github.com/user-attachments/files/17184090/jobs_202409301123.csv)

[job_params_training_202409301123.csv](https://github.com/user-attachments/files/17184091/job_params_training_202409301123.csv)

**Comment by rassokhina-e** [comment]
I found a problem. Look at here, when you go to the Training Set you will see this message:
<img width="1511" alt="Screenshot 2024-09-30 at 14 22 59" src="https://github.com/user-attachments/assets/0a0faa0d-e018-4dda-9113-0625ca141c52">

**Comment by rassokhina-e** [comment]
It means the user should draw the training set box on the visualizer, there is an instruction here: https://help.arbimon.org/article/232-creating-a-training-set-pattern
<img width="1017" alt="Screenshot 2024-09-30 at 14 24 31" src="https://github.com/user-attachments/assets/fe840345-e447-4585-a489-fd8b5cd7820a">

**Comment by rassokhina-e** [comment]
@koonchaya can you please check this support link and navigate the user for the next step?

**Comment by rassokhina-e** [comment]
the result for the training set should be the roi image inside the form:
https://help.arbimon.org/article/235-managing-training-sets
<img width="1025" alt="Screenshot 2024-09-30 at 14 28 11" src="https://github.com/user-attachments/assets/b74be6e9-8ece-4d3a-8168-a2e650d658c7">

**Comment by koonchaya** [comment]
Got it. Thanks @rassokhina-e
