### ISSUE TITLE
Clustering jobs grid view page has a problem with roi images

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/arbimon#2111]
([more detail](https://rfcx.slack.com/archives/C07TJFBLV6Z/p1730016387897419))

```
{
        "aed_id": 148981467,
        "time_min": 11.8507,
        "time_max": 12.96,
        "frequency_min": 187.5,
        "frequency_max": 2812.5,
        "recording_id": 11503436,
        "uri": null,
        "validated": null,
        "species_id": null,
        "songtype_id": null,
        "songtype": null,
        "scientific_name": null
    },
```

![Screenshot 2567-10-27 at 15 05 41](https://github.com/user-attachments/assets/40026a25-1f05-498a-b641-97a2e1164d2b)

**Comment by rassokhina-e** [comment]
related ticket https://github.com/rfcx/arbimon/issues/2115

**Comment by rassokhina-e** [comment]
there is a problem with images after the db upgrate, we are working with this problem

@koonchaya FYI
