### ISSUE TITLE
Add members on rfcx.org/team

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2114]
Add these following members to rfcx.org/team

- [x] Dr. Palitha  Gurusinghe - Project Director
![Image](https://github.com/user-attachments/assets/eeb2d6bb-b81f-4b38-ae41-6064fc984fc3)

- [x] Samitha Surendra - Marketing Director
![Image](https://github.com/user-attachments/assets/dcef141f-9031-4a92-a4a6-d8812c2eaba0)

- [x] Dilkumar Rai - Logistics Coordinator
![Image](https://github.com/user-attachments/assets/ad735790-dad6-4d75-824b-fb8825ed1346)

- [x] Dilini Perera - Customer Service
![Image](https://github.com/user-attachments/assets/df716d53-a483-46b8-b26b-9a32d3b03d5e)

- [x] Parvene Michaels - Business Development
![Image](https://github.com/user-attachments/assets/ec4aa243-e618-4a48-9302-2abe2ab8ea4d)

**Comment by RatreeOchn** [comment]
<img width="1349" alt="Screenshot 2567-11-18 at 12 56 21" src="https://github.com/user-attachments/assets/339fc688-efd2-49d1-92c8-5ee595f438af">
