### ISSUE TITLE
No data in clustering

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2115]
From: jlha0001@stud.slu.se

User was using clustering and listening to the files from clusters. Now it shows no data and user gets error.

Project https://arbimon.org/p/farna-pilot/overview
Job example: https://arbimon.org/project/farna-pilot/analysis/clustering-jobs

>I am listening through the files from the cluster jobs. However, it says 'No data for clustering job found' and 'Error communicating with server.' What could be causing this? I need access to the audio files as soon as possible.

![Image](https://github.com/user-attachments/assets/e826d432-775b-4080-bdaa-41e6fc763873)
![Image](https://github.com/user-attachments/assets/003886d2-689d-417a-97b0-735a46279dd2)

**Comment by koonchaya** [comment]
Error when open the job
![Image](https://github.com/user-attachments/assets/4a106b28-1ab4-4bde-a480-6d193d9bb82f)

Error when click play roi
![Image](https://github.com/user-attachments/assets/c4819e3d-f591-415d-a17c-b49d65c8c99b)

**Comment by rassokhina-e** [comment]
related original ticket is https://github.com/rfcx/arbimon/issues/2111
