### ISSUE TITLE
Enable AED and clustering

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2124]
- [x] Enable buttons
- [x] Can create job
- [x] Job complete
- [x] See result

**Comment by rassokhina-e** [comment]
<img width="1223" alt="Screenshot 2024-11-11 at 12 21 01" src="https://github.com/user-attachments/assets/aa2d8cd5-b1f8-4c0e-a049-5cfa92d97f23">

<img width="1439" alt="Screenshot 2024-11-11 at 12 21 08" src="https://github.com/user-attachments/assets/94db2b8b-5f67-43b6-b341-29521d5a9fff">

<img width="1027" alt="Screenshot 2024-11-11 at 12 21 28" src="https://github.com/user-attachments/assets/8b2b3acf-d7d2-4364-81a7-7d8d08d15503">

**Comment by rassokhina-e** [comment]
CLUSTERING JOB
<img width="1493" alt="Screenshot 2024-11-11 at 12 23 15" src="https://github.com/user-attachments/assets/5f243e34-7351-404b-a62c-0036317c8402">

<img width="1352" alt="Screenshot 2024-11-11 at 12 23 23" src="https://github.com/user-attachments/assets/c47e2ac1-ed52-4010-a88c-dcda3a10568b">
