### ISSUE TITLE
present_pm value >1 in recording validation project backup export

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2127]
From: benerguez@gmail.com

Project name: Puffinus puffinus - Tenerife 2021

What is the meaning of the number in the column name present_pm in the export file. User wonders why the number is >1.

![Image](https://github.com/user-attachments/assets/6bbeeb29-594f-405b-916d-8b0c3d6ac562)

**Comment by RatreeOchn** [comment]
[recording_validations_202411080929.csv](https://github.com/user-attachments/files/17671819/recording_validations_202411080929.csv)
