### ISSUE TITLE
User doesn't get the recording export

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2130]
From: tiena.danner@protonmail.com / Tiena Danner

Project: https://arbimon.org/p/sperlingskauz-rufphanologie/overview

>first of all - this is an amazing platform, thanks for putting in the work and providing such powerful tools for free in biodiversity research!

> However, I seem to be having a technical issue with exporting data from the project, i.e., I would like to download/export the data of the pattern matching results over the full project (all validated instances) from the recordings (explore --> recordings --> export --> export data). It says I should receive an e-mail with the exported data. The e-mail does not seem to come through though (it's not in the spam folder - I checked). My colleagues seem to experience the same problem.

**Comment by rassokhina-e** [comment]
I fixed the job on Friday, 3 report were processed by export job

<img width="1029" alt="Screenshot 2024-11-11 at 12 29 46" src="https://github.com/user-attachments/assets/951b77ba-2bd5-41dd-ad3c-ca7f778923a3">
