### ISSUE TITLE
User doesn't get recording export

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2145]
From: [calyptura@gmail.com](mailto:calyptura@gmail.com)

Project https://arbimon.org/p/fazenda-bananal/overview

>I am experiencing an issue with the "Export" option in the Explore/Recordings section. I attempted to use it yesterday and today, but I haven't received anything in my email.

**Comment by rassokhina-e** [comment]
the job cannot send the email, it takes to fix email service

**Comment by rassokhina-e** [comment]
Done
